name: pub_cache_server
description: A Pub server that serves from your device's Pub cache. Can be used for serving packages to an otherwise-offline device
version: 1.0.2
repository: https://github.com/Levi-Lesches/pub_cache_server

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  tar: ^2.0.0

dev_dependencies:
  very_good_analysis: ^10.0.0

executables:
  pub_cache_server:
